package mock

import (
	d "github.com/alnah/go-tmdb-cli/internal/data"
)

var FakeMovies = d.Movies{
	d.Movie{
		Id:            1,
		Date:          "2023-01-01",
		OriginalTitle: "L'Aube de l'Aventure",
		Title:         "Epic Journey Begins",
		Average:       8.5,
		Votes:         100,
	},
	d.Movie{
		Id:            2,
		Date:          "2023-02-01",
		OriginalTitle: "Rise of the Heroes",
		Title:         "Rise of the Heroes",
		Average:       7.0,
		Votes:         50,
	},
	d.Movie{
		Id:            3,
		Date:          "2023-03-01",
		OriginalTitle: "O Confronto Final",
		Title:         "Clash of Titans",
		Average:       9.0,
		Votes:         200,
	},
	d.Movie{
		Id:            4,
		Date:          "2023-04-01",
		OriginalTitle: "The Quest for Knowledge",
		Title:         "À la recherche du savoir",
		Average:       8.0,
		Votes:         75,
	},
	d.Movie{
		Id:            5,
		Date:          "2023-05-01",
		OriginalTitle: "A Ascensão da Inovação",
		Title:         "Rise of Innovation",
		Average:       7.5,
		Votes:         120,
	},
	d.Movie{
		Id:            6,
		Date:          "2023-06-01",
		OriginalTitle: "L'Aube d'une Nouvelle Ère",
		Title:         "A New Dawn",
		Average:       8.2,
		Votes:         90,
	},
	d.Movie{
		Id:            7,
		Date:          "2023-07-01",
		OriginalTitle: "A Última Resistência",
		Title:         "The Final Stand",
		Average:       9.1,
		Votes:         150,
	},
	d.Movie{
		Id:            8,
		Date:          "2023-08-01",
		OriginalTitle: "La Grande Aventure",
		Title:         "The Great Adventure",
		Average:       8.7,
		Votes:         200,
	},
	d.Movie{
		Id:            9,
		Date:          "2023-09-01",
		OriginalTitle: "A Jornada Continua",
		Title:         "The Journey Continues",
		Average:       7.8,
		Votes:         110,
	},
	d.Movie{
		Id:            10,
		Date:          "2023-10-01",
		OriginalTitle: "L'Héritage des Héros",
		Title:         "The Legacy of Heroes",
		Average:       9.3,
		Votes:         250,
	},
	d.Movie{
		Id:            11,
		Date:          "2023-11-01",
		OriginalTitle: "O Poder da Unidade",
		Title:         "The Power of Unity",
		Average:       8.4,
		Votes:         130,
	},
	d.Movie{
		Id:            12,
		Date:          "2023-12-01",
		OriginalTitle: "L'Appel à l'Aventure",
		Title:         "The Call of Adventure",
		Average:       8.9,
		Votes:         180,
	},
	d.Movie{
		Id:            13,
		Date:          "2024-01-01",
		OriginalTitle: "A Ascensão da Fênix",
		Title:         "The Rise of the Phoenix",
		Average:       9.0,
		Votes:         220,
	},
	d.Movie{
		Id:            14,
		Date:          "2024-02-01",
		OriginalTitle: "Le Voyage d'une Vie",
		Title:         "The Journey of a Lifetime",
		Average:       7.6,
		Votes:         95,
	},
	d.Movie{
		Id:            15,
		Date:          "2024-03-01",
		OriginalTitle: "O Coração de um Campeão",
		Title:         "The Heart of a Champion",
		Average:       8.3,
		Votes:         140,
	},
	d.Movie{
		Id:            16,
		Date:          "2024-04-01",
		OriginalTitle: "L'Esprit d'Aventure",
		Title:         "The Spirit of Adventure",
		Average:       8.1,
		Votes:         115,
	},
	d.Movie{
		Id:            17,
		Date:          "2024-05-01",
		OriginalTitle: "O Legado dos Bravos",
		Title:         "The Legacy of the Brave",
		Average:       9.2,
		Votes:         260,
	},
	d.Movie{
		Id:            18,
		Date:          "2024-06-01",
		OriginalTitle: "Le Pouvoir des Rêves",
		Title:         "The Power of Dreams",
		Average:       8.6,
		Votes:         170,
	},
	d.Movie{
		Id:            19,
		Date:          "2024-07-01",
		OriginalTitle: "O Chamado do Destino",
		Title:         "The Call of Destiny",
		Average:       9.4,
		Votes:         300,
	},
	d.Movie{
		Id:            20,
		Date:          "2024-08-01",
		OriginalTitle: "Le Voyage de l'Espoir",
		Title:         "The Journey of Hope",
		Average:       8.8,
		Votes:         190,
	},
	d.Movie{
		Id:            21,
		Date:          "2024-09-01",
		OriginalTitle: "A Ascensão dos Titãs",
		Title:         "The Rise of the Titans",
		Average:       9.1,
		Votes:         240,
	},
	d.Movie{
		Id:            22,
		Date:          "2024-10-01",
		OriginalTitle: "Le Cœur de l'Océan",
		Title:         "The Heart of the Ocean",
		Average:       8.5,
		Votes:         160,
	},
	d.Movie{
		Id:            23,
		Date:          "2024-11-01",
		OriginalTitle: "O Espírito da Floresta",
		Title:         "The Spirit of the Forest",
		Average:       8.0,
		Votes:         130,
	},
	d.Movie{
		Id:            24,
		Date:          "2024-12-01",
		OriginalTitle: "L'Appel de la Nature",
		Title:         "The Call of the Wild",
		Average:       9.0,
		Votes:         210,
	},
	d.Movie{
		Id:            25,
		Date:          "2025-01-01",
		OriginalTitle: "A Jornada das Estrelas",
		Title:         "The Journey of the Stars",
		Average:       8.4,
		Votes:         175,
	},
	d.Movie{
		Id:            26,
		Date:          "2025-02-01",
		OriginalTitle: "La Montée des Gardiens",
		Title:         "The Rise of the Guardians",
		Average:       9.3,
		Votes:         280,
	},
	d.Movie{
		Id:            27,
		Date:          "2025-03-01",
		OriginalTitle: "O Coração do Guerreiro",
		Title:         "The Heart of the Warrior",
		Average:       8.7,
		Votes:         150,
	},
	d.Movie{
		Id:            28,
		Date:          "2025-04-01",
		OriginalTitle: "L'Esprit du Ciel",
		Title:         "The Spirit of the Sky",
		Average:       8.9,
		Votes:         165,
	},
	d.Movie{
		Id:            29,
		Date:          "2025-05-01",
		OriginalTitle: "A Lenda do Dragão",
		Title:         "The Legend of the Dragon",
		Average:       9.5,
		Votes:         300,
	},
	d.Movie{
		Id:            30,
		Date:          "2025-06-01",
		OriginalTitle: "Le Dernier Voyage",
		Title:         "The Last Voyage",
		Average:       8.3,
		Votes:         140,
	},
	d.Movie{
		Id:            31,
		Date:          "2025-07-01",
		OriginalTitle: "O Caminho da Esperança",
		Title:         "The Path of Hope",
		Average:       8.6,
		Votes:         175,
	},
	d.Movie{
		Id:            32,
		Date:          "2025-08-01",
		OriginalTitle: "La Lumière de l'Aube",
		Title:         "The Light of Dawn",
		Average:       9.0,
		Votes:         200,
	},
	d.Movie{
		Id:            33,
		Date:          "2025-09-01",
		OriginalTitle: "A Última Esperança",
		Title:         "The Last Hope",
		Average:       9.2,
		Votes:         220,
	},
	d.Movie{
		Id:            34,
		Date:          "2025-10-01",
		OriginalTitle: "Le Voyage des Rêves",
		Title:         "The Journey of Dreams",
		Average:       8.8,
		Votes:         190,
	},
	d.Movie{
		Id:            35,
		Date:          "2025-11-01",
		OriginalTitle: "O Chamado da Aventura",
		Title:         "The Call of Adventure",
		Average:       9.1,
		Votes:         210,
	},
	d.Movie{
		Id:            36,
		Date:          "2025-12-01",
		OriginalTitle: "La Force de l'Amitié",
		Title:         "The Strength of Friendship",
		Average:       8.4,
		Votes:         160,
	},
	d.Movie{
		Id:            37,
		Date:          "2026-01-01",
		OriginalTitle: "A Jornada do Guerreiro",
		Title:         "The Warrior's Journey",
		Average:       9.3,
		Votes:         250,
	},
	d.Movie{
		Id:            38,
		Date:          "2026-02-01",
		OriginalTitle: "Le Dernier Héros",
		Title:         "The Last Hero",
		Average:       8.7,
		Votes:         180,
	},
	d.Movie{
		Id:            39,
		Date:          "2026-03-01",
		OriginalTitle: "O Legado dos Heróis",
		Title:         "The Legacy of Heroes",
		Average:       9.0,
		Votes:         230,
	},
	d.Movie{
		Id:            40,
		Date:          "2026-04-01",
		OriginalTitle: "La Quête de la Vérité",
		Title:         "The Quest for Truth",
		Average:       8.5,
		Votes:         200,
	},
}
